DOCSP-44873 1.44.6 Release Notes
mongodb/docs-compass pull request #691
Opened 2024-10-31 15:37 UTC by kennethdyer

## DESCRIPTION

Release notes 1.44.6.

## STAGING

## JIRA

## BUILD LOG

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-10-31 16:49 UTC, jmd-mongo requested changes
Thanks for these release notes, @kennethdyer! I noted a small typo.

Thanks,
Joe

2024-10-31 16:49 UTC, jmd-mongo commented on source/release-notes.txt
> +  aggregation genai :issue:`COMPASS-8369`)
[typo]

Missing open parens on line 19.

2024-10-31 18:45 UTC, kennethdyer commented on source/release-notes.txt
> +  aggregation genai :issue:`COMPASS-8369`)
Good catch. Fixed.

2024-10-31 18:54 UTC, jmd-mongo approved these changes
Thanks, @kennethdyer! This one LGTM.

Thanks,
Joe

2024-11-12 16:56 UTC, paula-stacho approved these changes

2024-11-14 15:52 UTC, merged